on:
  push:
    branches:
      - '**'

name: Discord Notification

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notifier
        uses: actions/checkout@v2
      - uses: fateyan/action-discord-notifier@v1.2.0
        with:
          message-title: New Commits Pushed
          webhook: https://discordapp.com/api/00000000000/secret
